### DISCUSSION TITLE
What should be in the config file for distributed deployment?

### DISCUSSION THREAD

**Discussion by housengw** [lf-lang/lingua-franca#1010] [General]
A common approach to deploying distributed programs is to specify parameters in a config file. 
For LF, what should be in the config file?

I bring this up because it seems to me that parameters in the config file need to be run-time properties instead of compile time properties, which would influence the design of LF. 

For example, if we want to specify the coordination type of the federation, we need to be able to change that during run time. 

So far I have come up with the following fields, using the [TOML](https://toml.io/en/) syntax:
```toml
[cluster]
name = "example_cluster"
node_type = "some node type"

[provider]
name = "aws" # or other providers, or "local" for local deployment

[docker]
image = "url to docker image"
run_options = "flags (--rm, -it, etc...)"
container_name = "name of container"

[scheduler]
name = "name of scheduler"
dynamic = true # or false

[federation]
coordinationType = "centralized or decentralized"
rtiAddr = "location of the rti or auto"
```
