### ISSUE TITLE
.github/workflows/README.md outdated.

### ISSUE THREAD

**Issue by Jakio815** [lf-lang/lingua-franca#2074]
Looks like [this](https://github.com/lf-lang/lingua-franca/blob/master/.github/workflows/README.md) is outdated. The `ci.yml` does not exist anymore.

Could anyone help updating this? I'm not sure how I can make my work in `reactor-c` get reflected in the CI tests.

**Comment by axmmisaka** [comment]
Maybe try specifying `runtime-ref`?

**Comment by Jakio815** [comment]
> Maybe try specifying `runtime-ref`?

@axmmisaka Should I just change it to true? Will it checkout the submodule I updated?

**Comment by axmmisaka** [comment]
I think it takes a ref, i.e. branch name or SHA

**Comment by Jakio815** [comment]
In `.github/workflows/c-tests.yml`
```
...
      runtime-ref:
        required: true
        type: string

...
      - name: Check out specific ref of reactor-c
        uses: actions/checkout@v3
        with:
          repository: lf-lang/reactor-c
          path: core/src/main/resources/lib/c/reactor-c
          # ref: ${{ inputs.runtime-ref }}
          ref: 'my_branch'
        if: ${{ inputs.runtime-ref }}
...
```
I think this part is where we should change, but it's not actually working. 
The `if` state should be true, which I changed it from the inputs.runtime-ref, and I don't know where I should point my branch.

I also tried just leaving `ref: ${{ inputs.runtime-ref }}` but still does not work.
